config/routes.rb
Rails.application.routes.draw do
 

  resources :pages 
  resources :items
  resources :orders
  resources :carts 
  get 'cart/index'

  resources :orders 
  devise_for :users
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'carts#emptyCart'
  get '/cart/:id' => 'carts#add' 
  get '/order/new' => 'orders#new'
  get '/cart/checkout' => 'carts#checkout'
  get '/users' => 'users#index'
  get '/cart/remove' => 'carts#remove'
  get '/item/update' => 'items#updateitem'

  root :to => 'pages#index'

  devise_scope :user do
   delete "/users/sign_out" => "devise/sessions#destroy"
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :item_carts
  has_many :items, through: :item_carts
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /carts
  # GET /carts.json
  def checkout
    #@carts.each do |c|
      @order = Order.new
      @order.item_ordered = params[:itemid]
      @order.user_id = params[:user_id] 
      @order.orderdate = Datetime.now
      @order.save
    #end
  end

  
  def index
    if session[:cart] then
      @cart = session[:cart]
    else
      @cart = {}
    end
  end
#--------------------------------------------------------------
  def add
      item_id = params[:id]
      if session[:cart] then
        cart = session[:cart]
      else
        session[:cart] = {}
        cart = session[:cart]
      end
 

  # check if item was already in the cart 
  # if it is incerement the qunatity'
  # otherwise quntitity is 1
    if cart[item_id] then
      cart[item_id] += 1
    else
      cart[item_id] = 1
    end
      redirect_to :action => :index   
  end
  #---------------------------------------------------------------------
  #clear a cart
  def emptyCart

    session[:cart] = {}
    redirect_to :action => :index
  end
  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  def remove
    #item_id = params[:item_id]
    #@cart.item = nil
    #redirect_to :action => :index
  end
  # GET /carts/new
  # the user_id associated with cart is the current user_id
  def new
    @cart = Cart.new
    @cart.user_id = current_user.id
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)
    @cart.user_id = current_user.id

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:user_id)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div> 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Items in Your Cart</h1>  

<%if @cart.empty? %>
  <p> Your Cart is Currently Empty </p>
  <p><b><%= link_to "Shop for Items", items_path %> <b> </p>
<% else %>
  <%= link_to 'Clear Cart', cart_clear_path %> &nbsp;&nbsp;
  <%= link_to 'ADD More Products', items_path %><br><br> 
<% end %>

<% total = 0 %>
 
<table> 
  <thead>
    <tr>
      <th>Item</th>
      <th>Price</th> 
    </tr>
  </thead>
  <tbody>
    <% @cart.each do | id | %>
    <% item = Item.find_by_id(id) %>
    <tr>
      <td><%= link_to item.name, item %></td>
      <td><%= number_to_currency(item.price ) %></td> 
        
    </tr>
      <% total = item.price %>

    <% end %>
  </tbody>   
 </table>
 <p><b> TOTAL: <%= number_to_currency(total)%> <b></p>

 <!-- This is teporarly to clear the cart, but it will be to
 process and place a new order by customer -->
<% if @cart.empty? %> 
  <%  else %>  
  <% @cart.each do | id | %>
    <% item = Item.find_by_id(id) %>  
      <%= link_to "Check Out", order_new_path(itemid: item.id, user_id: current_user.id)%>      
    <% end %>    
<% end %>

 

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @cart.user %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>