config/routes.rb
Rails.application.routes.draw do
 

  resources :pages 
  resources :items
  resources :orders
  resources :carts 
  get 'cart/index'

  resources :orders 
  devise_for :users
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'carts#emptyCart'
  get '/cart/:id' => 'carts#add' 
  get '/order/new' => 'orders#new'
  get '/cart/checkout' => 'carts#checkout'
  get '/users' => 'users#index'
  get '/cart/remove' => 'carts#remove'
  get '/item/update' => 'items#updateitem'

  root :to => 'pages#index'

  devise_scope :user do
   delete "/users/sign_out" => "devise/sessions#destroy"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingCart</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> 
  <%= csrf_meta_tags %>
</head>
<body>
	 
<nav id="navigation">
	<div id="menu_nav"> 
		<%= link_to "Home",items_path %> &nbsp;&nbsp;
		<%= link_to "Shop",items_path %> &nbsp;&nbsp; 
		<%if current_user %>
			<%= link_to "View Cart",carts_path %>
		<%end%>	
      <!-- show orders that belongs to current user-->
		<% if user_signed_in? %>&nbsp;&nbsp;  
			<%= link_to "My Orders",orders_path%>
	    <%end%>
     
   <span id="user_session"> 
	<% if user_signed_in? %> 
		<%= current_user.email %>
		<%= link_to "Sign Out",users_sign_out_path, method: :delete 
	%>
	<% else %>
		<%= link_to "Sign In",new_user_session_path %> &nbsp;&nbsp;
		<%= link_to "Sign Up",new_user_registration_path %>&nbsp;&nbsp;
		 
	<%end%>
	 
	</span>
	</div>
</nav><hr>
<div id="admin_menu">
	<!-- only if the current user has admin proivilage, then he/she can modify products -->
	<% if current_user %>
		<% if current_user.email == "admin@admin.com" %>
		 	<u><h3 align="center">Shopkeeper Dashboard</h3></u> <br>
		 	<%= link_to "Add or Update Product", items_path %> &nbsp;&nbsp;&nbsp;&nbsp;
		 	<%= link_to "View Recent Orders", orders_path %>
		 <%end%>
	<%end%>
</div> <br><br>
 
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
<%= yield %>

<div id="footer"> 
	 
	<%= link_to "Home",items_path %> &nbsp;&nbsp; 

	<p>Copyright &copy; Asefaw Mekuria</p><hr>
</div>
</body>
</html>